### ISSUE TITLE
Images fail downloading with error code 35

### ISSUE THREAD

**Issue by profi200** [Slluxx/AmiiboGenerator#2]
I'm not sure if this is a problem with this app or the database but almost all images fail to download now with error code 35. This worked fine last week. The database and Amiibo data does download fine.

Atmosphere 1.5.3, firmware 16.0.3.
Version is the latest offered by hb-appstore (v1.4.0).

**Comment by naddel91** [comment]
same here. no download possible.

**Comment by profi200** [comment]
I ended up using emutool for those who need a solution. That worked flawlessly first try. So i guess something is wrong with this hb app. Assuming error 35 is a curl error then something is wrong with the certificates i guess:

`CURLE_SSL_CONNECT_ERROR (35)`
`A problem occurred somewhere in the SSL/TLS handshake. You really want the error buffer and read the message there as it pinpoints the problem slightly more. Could be certificates (file formats, paths, permissions), passwords, and others.`

**Comment by Slluxx** [comment]
Sounds like you guys used incognito?

**Comment by profi200** [comment]
Prodinfo blanking, yes. Didn't actually overwrite prodinfo at all and it used to work.

**Comment by Slluxx** [comment]
that messes with SSL certificates, nothing i will fix
