### ISSUE TITLE
"head" and "tail" values

### ISSUE THREAD

**Issue by GitGitHubUser** [Slluxx/AmiiboGenerator#3]
Hello,
I hope you can help me - in the JSON file there are two values for each Amiibo - "head" and "value", which are coming from the dump files. Could you explain please, where to find these values in the dump files? Thanks!

**Comment by Slluxx** [comment]
I don't quite understand your question. 

These values inside the generated amiibo files come from the json API, and not the other way around. [Here is the API url](https://www.amiiboapi.com/).

Head and tail are combined into a 16 character string and then used as ["model_number"](https://github.com/Slluxx/AmiiboGenerator/blob/main/source/amiibo.hpp#L84) to generate a new `amiibo.json` file.
